Internal Server Error: /api/items/18
Traceback (most recent call last):
  File "/home/benson/Documents/Kaizntree/kenv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/benson/Documents/Kaizntree/kenv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/benson/Documents/Kaizntree/kenv/lib/python3.10/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/benson/Documents/Kaizntree/kenv/lib/python3.10/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to localhost:8000/api/items/18/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"PUT /api/items/18 HTTP/1.1" 500 77554
You're accessing the development server over HTTPS, but it only supports HTTP.
